apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-v
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/docker/nginxPhpFpm/app/