apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: my-php-app
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: my-php-app
    spec:
      containers:
      - name: mysql
        image: mariadb
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-vm
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
      volumes:
      - name: mysql-vm
        persistentVolumeClaim:
          claimName: mysql-pvc